import Head from "next/head";
import styles from '../components/page.module.css';
import Link from "next/link";
import { useState } from "react";

export default function Header() {
  const [showForm, setShowForm] = useState(false);

  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['body1']}>
        <header className={styles['header']}>
          <nav className={styles['nav']}>
            <div className={styles['logo']}>LOGO</div>
            <ul className={styles['ul']}>
              <li className={styles['li']}><Link className={styles['link']} href="#">Home</Link></li>
              <li className={styles['li']}><Link className={styles['link']} href="#">About</Link></li>
              <li className={styles['li']}><Link className={styles['link']} href="#">Services</Link></li>
              <li className={styles['li']}><Link className={styles['link']} href="#">Contact</Link></li>
              <li className={styles['li']}>
                <button 
                  className={styles['loginBtn']} 
                  onClick={() => setShowForm(!showForm)}
                >
                  Login
                </button>
              </li>
            </ul>
          </nav>
        </header>

        {showForm && (
          <div className={styles['form-div']}>
            <form className={styles['form']}>
              <h1 style={{color: 'white'}}>Get Started Now</h1>
              <div className={styles["formInput"]}>
                <p className={styles['p']}>Name</p>
                <input className={styles['input']} type="text" placeholder='Enter your name' />
              </div>
              <div className="formInput">
                <p className={styles['p']}>Email address</p>
                <input className={styles['input']} type="email" placeholder='Enter your email' />
              </div>
              <div className="formInput">
                <p className={styles['p']}>Password</p>
                <input className={styles['input']} type="password" placeholder='Enter your password' />
              </div>
              <div className={styles["remember-forgot"]}>
                <input style={{ marginRight: '5px', color: 'white' }} className={styles['input1']} type="checkbox" />
                <p className={styles['p']}>I agree to the terms & policy</p>
              </div>
              <button className={styles['singUp']}>Sign up</button>
              <div className={styles["haveAcc"]}>
                <p style={{ marginRight: '5px', color: 'white' }}>Have an account?</p>
                <Link href="#" className={styles['singIn']}>Sign In</Link>
              </div>
            </form>
          </div>
        )}
      </div>
    </>
  );
}
